{
  "name": "PiAware + tar1090 Add-on",
  "version": "1.0.0",
  "slug": "piaware-tar1090",
  "description": "Wraps the Tar1090 web interface for remote PiAware connectivity with automatic dashboard integration.",
  "startup": "services",
  "ingress": true,
  "arch": ["armhf", "armv7", "aarch64", "amd64"],
  "ports": {
    "8080/tcp": 8080
  },
  "options": {
    "piaware_host": "http://piaware"
  },
  "schema": {
    "piaware_host": "string"
  }
}
